### ISSUE TITLE
Refresh submits new video task

### ISSUE THREAD

**Issue by newburns** [lbdc/zm-movie#10]
After initial submission, all variables are still available in the URL.
A refresh causes the job to resubmit without the ability to kill those jobs.
Just the ability to kill the latest job

**Comment by lbdc** [comment]
The script unset the $_GET and $_REQUEST as well as reloads the header location after submission which clears the fields my installation (Ubuntu/Firefox). What browser are you using? This is a not a problem I am encountering.

Because of the above, the repost is causing two mencoder instances generating the same file name. I will correct this in case a user accidently reposts the same filename.
